name: yandex_mapkit_lite_initializer
description: Initializes Yandex MapKit Lite on Android and iOS (works with FlutterFlow)
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # сам MapKit Lite подтягивается из твоего основного проекта, но можно продублировать:
  # yandex_maps_mapkit_lite: ^4.30.0-beta

flutter:
  plugin:
    platforms:
      android:
        package: com.mycompany.yandex_mapkit_lite_initializer
        pluginClass: YandexMapKitLiteInitializerPlugin
      ios:
        pluginClass: YandexMapKitLiteInitializerPlugin
